export const data = [
  {
    firstname: 'Thtitiwut',
    lastname: 'Somsa',
    displayName: 'Araiva',
    avatar: 'https://avatars.dicebear.com/v2/female/0a0f462976f9dfbd41cae13b86e1c011.svg',
    age: 30,
    scores: [
      { game: 'O2Jam', point: 99 },
      { game: 'Dota2', point: 70 },
      { game: 'Final Fantasy', point: 85 },
      { game: 'Sekiro', point: 70 },
    ]
  },
  {
    firstname: 'Harry',
    lastname: 'Taylor',
    displayName: 'Swift',
    avatar: 'https://avatars.dicebear.com/v2/female/40e3e9bb1d742abe29cf2568076dd489.svg',
    age: 32,
    scores: [
      { game: 'O2Jam', point: 20 },
      { game: 'Dota2', point: 50 },
      { game: 'Final Fantasy', point: 35 },
      { game: 'Sekiro', point: 90 },
    ],
  },
  {
    firstname: 'Alfie',
    lastname: 'Smith',
    displayName: 'Smithy',
    avatar: 'https://avatars.dicebear.com/v2/female/1c789fd3a30e460e64281f762841195b.svg',
    age: 28,
    scores: [
      { game: 'O2Jam', point: 44 },
      { game: 'Dota2', point: 12 },
      { game: 'Final Fantasy', point: 91 },
      { game: 'Sekiro', point: 32 },
    ],
  },
  {
    firstname: 'Oliver',
    lastname: 'Jones',
    displayName: 'Oli',
    avatar: 'https://avatars.dicebear.com/v2/female/44be3d23db067a63801d8d92181873a1.svg',
    age: 22,
    scores: [
      { game: 'O2Jam', point: 12 },
      { game: 'Dota2', point: 55 },
      { game: 'Final Fantasy', point: 23 },
      { game: 'Sekiro', point: 56 },
    ],
  },
  {
    firstname: 'Joshua',
    lastname: 'Wilson',
    displayName: 'Joe',
    avatar: 'https://avatars.dicebear.com/v2/female/2a7e55e6e81731d37e067de47cd73ff4.svg',
    age: 20,
    scores: [
      { game: 'O2Jam', point: 45 },
      { game: 'Dota2', point: 78 },
      { game: 'Final Fantasy', point: 12 },
      { game: 'Sekiro', point: 34 },
    ],
  },
  {
    firstname: 'James',
    lastname: 'Moore',
    displayName: 'Jim',
    avatar: 'https://avatars.dicebear.com/v2/female/953a5fb1b4fa3c0cde828a4415200b01.svg',
    age: 70,
    scores: [
      { game: 'O2Jam', point: 36 },
      { game: 'Dota2', point: 65 },
      { game: 'Final Fantasy', point: 34 },
      { game: 'Sekiro', point: 76 },
    ],
  },
  {
    firstname: 'Samuel',
    lastname: 'Thompson',
    displayName: 'Sami',
    avatar: 'https://avatars.dicebear.com/v2/female/412d2b9e892d53b3843662c5b87bfaef.svg',
    age: 70,
    scores: [
      { game: 'O2Jam', point: 66 },
      { game: 'Dota2', point: 23 },
      { game: 'Final Fantasy', point: 43 },
      { game: 'Sekiro', point: 21 },
    ],
  },
  {
    firstname: 'Arman',
    lastname: 'Poole',
    displayName: 'Arpo',
    avatar: 'https://avatars.dicebear.com/v2/female/51ee115db039dc709c07380fb59fe581.svg',
    age: 33,
    scores: [
      { game: 'O2Jam', point: 12 },
      { game: 'Dota2', point: 76 },
      { game: 'Final Fantasy', point: 21 },
      { game: 'Sekiro', point: 33 },
    ],
  },
  {
    firstname: 'Bernice',
    lastname: 'Zuniga',
    displayName: 'Arpo',
    avatar: 'https://avatars.dicebear.com/v2/female/47db735e96df32865a7fbcfcef6f8725.svg',
    age: 23,
    scores: [
      { game: 'O2Jam', point: 44 },
      { game: 'Dota2', point: 21 },
      { game: 'Final Fantasy', point: 87 },
      { game: 'Sekiro', point: 67 },
    ],
  },
  {
    firstname: 'Jo',
    lastname: 'Gamble',
    displayName: 'Gom',
    avatar: 'https://avatars.dicebear.com/v2/female/a84228138a6294c7f3ab198defde70d4.svg',
    age: 56,
    scores: [
      { game: 'O2Jam', point: 22 },
      { game: 'Dota2', point: 33 },
      { game: 'Final Fantasy', point: 22 },
      { game: 'Sekiro', point: 88 },
    ],
  },
  {
    firstname: 'Ruben',
    lastname: 'O\'Doherty',
    displayName: 'Ruo',
    avatar: 'https://avatars.dicebear.com/v2/female/39efaa21632d58549596e78ef6c16ea4.svg',
    age: 76,
    scores: [
      { game: 'O2Jam', point: 43 },
      { game: 'Dota2', point: 23 },
      { game: 'Final Fantasy', point: 67 },
      { game: 'Sekiro', point: 78 },
    ],
  },
  {
    firstname: 'Nathanael',
    lastname: 'Conroy',
    displayName: 'Nat',
    avatar: 'https://avatars.dicebear.com/v2/female/96b20fa3b45d666270ebb65343e70685.svg',
    age: 76,
    scores: [
      { game: 'O2Jam', point: 56 },
      { game: 'Dota2', point: 22 },
      { game: 'Final Fantasy', point: 57 },
      { game: 'Sekiro', point: 83 },
    ],
  }
];
